#!/usr/bin/python3

import json
from bottle import route, run, request#, static_file
from libaqueductbuilder import conf, pkg_build



@route('/', method='GET')
def get_info():
	info = {
		'name' : 'aqueduct-builder',
		'version' : conf['version'],
		'arch' : conf['arch']
		}
	return json.dumps(info)



@route('/build/submit', method='POST')
def build_submit():
	upload = request.files.data
	callbackurl = request.forms.get('callbackurl')

	if not upload or not upload.file:
		return {'success' : False, 'message' : 'No file supplied'}
	elif not callbackurl:
		return {'success' : False, 'message' : 'No callback url supplied'}

	upload.save(conf['dir']['intake'])
	pkg_build('deb', conf['dir']['intake']+'/'+upload.filename)



@route('/build/<build_id>/log')
def build_log(build_id):
	return "not implimented yet"



@route('/build/<build_id>/result')
def build_result(build_id):
	return "not implimented yet"



run(host='', port=conf['port'], debug=True)
